# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_is_single_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Назначение заказа'),
        ),
    ]
