# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20171124_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order', 'location', 'price'], 'verbose_name': 'предмет сервиса', 'verbose_name_plural': 'предметы сервиса'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показа'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показа'),
        ),
    ]
