# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 19:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20171124_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-approved', '-date_start', 'time_start'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено'),
        ),
        migrations.AlterField(
            model_name='service',
            name='request_document',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'odt', 'png', 'jpg', 'jpeg'])], verbose_name='Служебка (doc/docx/pdf/odt/png/jpg/jpeg)'),
        ),
    ]
