# Generated by Django 2.0 on 2018-03-07 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20180304_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['is_approved', '-date_start', 'time_start'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='workingtime',
            old_name='weekend',
            new_name='is_weekend',
        ),
        migrations.RenameField(
            model_name='workingtimeexception',
            old_name='weekend',
            new_name='is_weekend',
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='works_from',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени (включительно)'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='works_to',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Конец рабочего времени (не включительно)'),
        ),
        migrations.AlterField(
            model_name='workingtimeexception',
            name='date_end',
            field=models.DateField(default=datetime.date.today, verbose_name='День окончания (включительно)'),
        ),
        migrations.AlterField(
            model_name='workingtimeexception',
            name='date_start',
            field=models.DateField(default=datetime.date.today, verbose_name='День начала (включительно)'),
        ),
        migrations.AlterField(
            model_name='workingtimeexception',
            name='works_from',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени (включительно)'),
        ),
        migrations.AlterField(
            model_name='workingtimeexception',
            name='works_to',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Конец рабочего времени (не включительно)'),
        ),
    ]
