# Generated by Django 2.0 on 2018-03-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20180307_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='time_step',
            new_name='timestep',
        ),
    ]
