# Generated by Django 2.0 on 2018-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20180407_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='late_cancel_multiplicator',
            field=models.FloatField(default=1.0, verbose_name='На сколько умножить при отмене'),
        ),
    ]
