# Generated by Django 2.0 on 2018-06-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_auto_20180623_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='max_time_steps',
            new_name='max_continuous_orders',
        ),
    ]
