# Generated by Django 2.0 on 2018-09-16 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_auto_20180623_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_margin_end',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время на вход после заказа'),
        ),
        migrations.AddField(
            model_name='service',
            name='time_margin_start',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время на вход до заказа'),
        ),
    ]
