# Generated by Django 2.1.1 on 2018-10-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_auto_20180926_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order', 'location', 'price'], 'verbose_name': '(устарело) Предмет сервиса', 'verbose_name_plural': '(устарело) Предметы сервиса'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['is_approved', '-date_start', '-time_start'], 'verbose_name': '(устарело) Заказ', 'verbose_name_plural': '(устарело) Заказы'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['-order', 'user'], 'verbose_name': '(устарело) Участие', 'verbose_name_plural': '(устарело) Участия'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': '(устарело) Сервис', 'verbose_name_plural': '(устарело) Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='workingtime',
            options={'ordering': ['object_id', 'weekday', 'works_from', 'works_to'], 'verbose_name': '(устарело) Время работы', 'verbose_name_plural': '(устарело) Расписания'},
        ),
        migrations.AlterModelOptions(
            name='workingtimeexception',
            options={'ordering': ['object_id', 'is_annual', 'date_start', 'date_end', 'works_from'], 'verbose_name': '(устарело) Дата исключения', 'verbose_name_plural': '(устарело) Даты исключений'},
        ),
    ]
