# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic_name', models.CharField(max_length=32, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Контактный номер')),
                ('account_url', models.CharField(max_length=64, unique=True, verbose_name='Аккаунт')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='Почта')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
