# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Почта'),
        ),
    ]
