# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170721_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=64, verbose_name='Почта'),
        ),
    ]
