# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170722_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_url',
            new_name='account_id',
        ),
    ]
