# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_adtive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
