# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170723_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_number',
            field=models.IntegerField(default=419, verbose_name='Номер группы'),
            preserve_default=False,
        ),
    ]
