# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170809_2126'),
        ('user', '0005_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='responcible_for',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Service'),
        ),
    ]
