# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170821_1538'),
        ('user', '0006_auto_20170809_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='responsible_for',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Service'),
        ),
    ]
