# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170809_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='UID карты'),
        ),
    ]
