# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_number',
            field=models.CharField(max_length=4, verbose_name='Номер группы'),
        ),
    ]
