# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170809_1308'),
        ('user', '0007_auto_20170809_2127'),
    ]

    operations = [
    ]
