# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_responsible_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='uid карты'),
        ),
    ]
