# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20171004_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Почта'),
        ),
    ]
