# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20171013_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['is_superuser', 'is_staff', 'group_number', 'last_name'], 'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
