# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20171014_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Счёт'),
        ),
    ]
