# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20171102_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Контактный номер'),
        ),
    ]
