# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20171108_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL аватарки'),
        ),
    ]
