# Generated by Django 2.0 on 2018-02-26 17:45

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20180226_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=user.models.make_random_password, max_length=25, verbose_name='Резервный пароль'),
        ),
    ]
