# Generated by Django 2.1.1 on 2018-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20181108_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_number',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Номер комнаты'),
        ),
    ]
