# Generated by Django 2.2.5 on 2020-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20181108_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL аватарки'),
        ),
    ]
