# Generated by Django 2.1.1 on 2018-10-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washing', '0002_auto_20181001_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washingmachine',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название/номер'),
        ),
    ]
