# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170803_1114'),
        ('news', '0002_auto_20170803_1149'),
    ]

    operations = [
    ]
