# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170809_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='_text_preview_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='_text_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_preview',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, verbose_name='Превью'),
        ),
    ]
