# Generated by Django 2.0 on 2018-04-07 22:43

import django.core.validators
from django.db import migrations
import utils.model_aliases


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180407_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=utils.model_aliases.DefaultImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg'])], verbose_name='Изображение (jpg, jpeg, png, gif, svg)'),
        ),
    ]
