# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170930_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='_text_preview_rendered',
        ),
        migrations.RemoveField(
            model_name='news',
            name='_text_rendered',
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_preview',
            field=models.TextField(blank=True, verbose_name='Превью'),
        ),
    ]
