# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20171003_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
