# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Последнее редактирование')),
                ('name', models.SlugField(max_length=16, verbose_name='Фрагмент URL на английском (навсегда)')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Заметку',
                'verbose_name_plural': 'Заметки',
                'ordering': ['name'],
            },
        ),
    ]
