# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['name'], 'verbose_name': 'Заметку', 'verbose_name_plural': 'Заметки'},
        ),
    ]
