# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.SlugField(max_length=16, verbose_name='Название'),
        ),
    ]
