# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20170809_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.SlugField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
