# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20170916_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.SlugField(max_length=16, unique=True, verbose_name='Название'),
        ),
    ]
