# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0005_auto_20171003_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('_text_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('text', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True, verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
    ]
