# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_question_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Автор виден всем'),
        ),
    ]
