# Generated by Django 2.0 on 2018-02-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0018_auto_20171227_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['is_approved', '-created'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
