# Generated by Django 2.1.1 on 2018-10-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название раздела')),
                ('url', models.CharField(max_length=64, verbose_name='Адрес')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показа')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
                'ordering': ['order'],
            },
        ),
    ]
