# Generated by Django 2.1.1 on 2018-10-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washing',
            name='max_continuous_orders',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Максимум непрерывных заказов одного предмета'),
        ),
    ]
