# Generated by Django 2.1.1 on 2018-10-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washing', '0004_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='used',
            new_name='is_used',
        ),
    ]
