# Generated by Django 2.0 on 2018-02-25 22:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180212_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'comment'), ('model', 'comment'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'note'), ('model', 'question'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип назначения'),
        ),
    ]
