# Generated by Django 2.0 on 2018-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20180409_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='_text_rendered',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=512, verbose_name='Текст'),
        ),
    ]
