# Generated by Django 2.1.1 on 2018-10-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='url',
            field=models.CharField(max_length=64, unique=True, verbose_name='Адрес'),
        ),
    ]
