# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=124, null=True, verbose_name='Расположение')),
                ('extra_info', models.CharField(blank=True, max_length=124, null=True, verbose_name='Доп. информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Предметы сервиса',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(unique=True, verbose_name='Время начала')),
                ('time_end', models.DateTimeField(unique=True, verbose_name='Время конца')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.Item', verbose_name='Предмет сервиса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(max_length=16, unique=True, verbose_name='Фрагмент URL на английском')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=124, verbose_name='Краткое описание')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Инструкция и подробное описание')),
                ('time_step', models.TimeField(verbose_name='Минимальное время использования (шаг времени)')),
                ('max_time_steps', models.IntegerField(default=1, verbose_name='Максимальное число шагов времени непрерывного использования')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена по-умолчанию за шаг времени')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Последнее редактирование этих данных')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.Service', verbose_name='Сервис'),
        ),
    ]
