# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 15:38
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье'), ('Eve', 'Ежедневно')], default='Eve', max_length=3, verbose_name='Рабочее время')),
                ('works_from', models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени')),
                ('works_to', models.TimeField(default=datetime.time(23, 59, 59), verbose_name='Конец рабочего времени')),
                ('object_id', models.PositiveIntegerField(verbose_name='Id назначения')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип назначения')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Расписания',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='WorkingTimeException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='День начала')),
                ('date_end', models.DateField(verbose_name='День окончания')),
                ('works_from', models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени')),
                ('works_to', models.TimeField(default=datetime.time(0, 0), verbose_name='Конец рабочего времени')),
                ('is_annual', models.BooleanField(default=False, verbose_name='Ежегодно')),
                ('object_id', models.PositiveIntegerField(verbose_name='Id назначения')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип назначения')),
            ],
            options={
                'verbose_name': 'Дата исключения',
                'verbose_name_plural': 'Даты исключений',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет сервиса', 'verbose_name_plural': 'Предметы сервиса'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Введено в строй'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Цена за шаг времени'),
        ),
        migrations.AddField(
            model_name='item',
            name='t_steps_per_order',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Число шагов времени на заказ'),
        ),
        migrations.AddField(
            model_name='service',
            name='days_to_show',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Дней на заказ'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Цена по-умолчанию за шаг времени'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_works_from',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени по-умолчанию'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_works_to',
            field=models.TimeField(default=datetime.time(23, 59, 59), verbose_name='Конец рабочего времени по-умолчанию'),
        ),
        migrations.AddField(
            model_name='service',
            name='time_after_now',
            field=models.TimeField(default=datetime.time(0, 20), verbose_name='Времени на запись после начала'),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_time_steps',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Максимальное число шагов времени непрерывного использования'),
        ),
        migrations.AlterUniqueTogether(
            name='workingtimeexception',
            unique_together=set([('content_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='workingtime',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
