# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет сервиса', 'verbose_name_plural': 'Предметы сервиса'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Введено в строй'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена за шаг времени'),
        ),
        migrations.AddField(
            model_name='service',
            name='works_from',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени'),
        ),
        migrations.AddField(
            model_name='service',
            name='works_to',
            field=models.TimeField(default=datetime.time(23, 59, 59), verbose_name='Конец рабочего времени'),
        ),
    ]
