# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 05:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service', '0002_auto_20170809_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье'), ('Eve', 'Ежедневно')], default='Eve', max_length=3, verbose_name='Рабочее время')),
                ('works_from', models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени')),
                ('works_to', models.TimeField(default=datetime.time(23, 59, 59), verbose_name='Конец рабочего времени')),
                ('object_id', models.PositiveIntegerField(verbose_name='Id назначения')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип назначения')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='WorkingTimeException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.DateField(verbose_name='День исключения')),
                ('duration', models.IntegerField(default=1, verbose_name='Продолжительность')),
                ('works_from', models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени')),
                ('works_to', models.TimeField(default=datetime.time(0, 0), verbose_name='Конец рабочего времени')),
            ],
            options={
                'verbose_name': 'Дата исключения',
                'verbose_name_plural': 'Даты исключения',
            },
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='default_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='works_from',
        ),
        migrations.RemoveField(
            model_name='service',
            name='works_to',
        ),
        migrations.AddField(
            model_name='service',
            name='default_works_from',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени по-умолчанию'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_works_to',
            field=models.TimeField(default=datetime.time(23, 59, 59), verbose_name='Конец рабочего времени по-умолчанию'),
        ),
        migrations.AddField(
            model_name='workingtimeexception',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to='service.Service', verbose_name='Сервис'),
        ),
        migrations.AlterUniqueTogether(
            name='workingtime',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
