# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170821_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workingtime',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='workingtimeexception',
            unique_together=set([]),
        ),
    ]
