# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20171102_0903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('date_start', 'time_start', 'item'), ('date_start', 'time_end', 'item')]),
        ),
    ]
