# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170818_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingtime',
            options={'ordering': ['weekday'], 'verbose_name': 'Время работы', 'verbose_name_plural': 'Расписания'},
        ),
    ]
