# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170829_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingtime',
            options={'ordering': ['weekday', 'works_from'], 'verbose_name': 'Время работы', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье'), ('8', 'Ежедневно')], default='8', verbose_name='Рабочее время'),
        ),
    ]
