# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170829_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingtime',
            options={'ordering': ['object_id', 'weekday', 'works_from', 'works_to'], 'verbose_name': 'Время работы', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='workingtimeexception',
            options={'ordering': ['object_id', 'is_annual', 'date_start', 'date_end', 'works_from'], 'verbose_name': 'Дата исключения', 'verbose_name_plural': 'Даты исключений'},
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье'), (8, 'Ежедневно')], default=8, verbose_name='Рабочее время'),
        ),
    ]
