# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_responsible_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['location', 'price'], 'verbose_name': 'Предмет сервиса', 'verbose_name_plural': 'Предметы сервиса'},
        ),
        migrations.AddField(
            model_name='workingtime',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='workingtimeexception',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Описание'),
        ),
    ]
