# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20170829_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='Название/номер'),
            preserve_default=False,
        ),
    ]
