# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_start',
            field=models.DateField(default=datetime.date(2017, 8, 30), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.TimeField(unique=True, verbose_name='Время конца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_start',
            field=models.TimeField(unique=True, verbose_name='Время начала'),
        ),
    ]
