# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20171124_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='text',
            new_name='title',
        ),
    ]
