# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20170830_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='weekend',
            field=models.BooleanField(default=False, verbose_name='Выходной'),
        ),
        migrations.AddField(
            model_name='workingtimeexception',
            name='weekend',
            field=models.BooleanField(default=False, verbose_name='Выходной'),
        ),
    ]
