# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 14:54
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20170830_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['location', 'price'], 'verbose_name': 'предмет сервиса', 'verbose_name_plural': 'предметы сервиса'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(default=datetime.date(2017, 9, 2), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='service',
            name='days_to_show',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Дней на заказ'),
        ),
    ]
