# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 06:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20170902_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(default=datetime.date(2017, 9, 4), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.TimeField(verbose_name='Время конца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_start',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('date_start', 'time_start'), ('date_start', 'time_end')]),
        ),
    ]
