# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 06:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20170904_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
