# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_participation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([]),
        ),
    ]
