# Generated by Django 2.0 on 2018-02-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20171228_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['approved', '-date_start', 'time_start'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Цена за шаг времени'),
        ),
    ]
