# Generated by Django 2.0 on 2018-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20180225_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='announcements',
            field=models.TextField(blank=True, max_length=124, null=True, verbose_name='Объявления'),
        ),
        migrations.AddField(
            model_name='service',
            name='responsible_room',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Комната ответственного'),
        ),
    ]
