# Generated by Django 2.0 on 2018-03-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20180310_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_finished_hidden',
            field=models.BooleanField(default=True, verbose_name='Скрывать прошедшие интервалы'),
        ),
    ]
