# Generated by Django 2.0 on 2018-03-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_service_is_finished_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Оплачено'),
            preserve_default=False,
        ),
    ]
