# Generated by Django 2.0 on 2018-06-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_auto_20180623_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_time_steps',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Максимум непрерывных заказов на одну машинку'),
        ),
    ]
