# Generated by Django 2.0 on 2018-09-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_service_disable_lock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['is_approved', '-date_start', '-time_start'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
