# Generated by Django 2.1.1 on 2018-10-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
