# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20170930_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='_text_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, verbose_name='Текст'),
        ),
    ]
