# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 18:20
from __future__ import unicode_literals

from django.db import migrations
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20171004_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, max_length=384, no_rendered_field=True, verbose_name='Текст'),
        ),
    ]
