# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20171004_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='edited',
            field=models.DateTimeField(auto_now=True, error_messages={'required': 'heh'}, verbose_name='Время редактирования'),
        ),
    ]
