# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_note_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Название'),
        ),
    ]
