# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0015_auto_20171026_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показа'),
        ),
    ]
