# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import note.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0016_auto_20171124_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=note.models.get_default_approved, verbose_name='Одобрено'),
        ),
    ]
