# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0017_question_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['is_approved', 'created'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
