# Generated by Django 2.0 on 2018-04-07 22:50

import django.core.validators
from django.db import migrations
import utils.model_aliases


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0022_auto_20180407_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='attachment',
            field=utils.model_aliases.DefaultDocumentField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'odt', 'xls', 'xlsx', 'ods', 'ppt', 'pptx', 'odp', 'jpg', 'jpeg', 'png', 'gif', 'svg'])], verbose_name='Дополнительное приложение (pdf, txt, doc, docx, odt, xls, xlsx, ods, ppt, pptx, odp, jpg, jpeg, png, gif, svg)'),
        ),
    ]
