# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170803_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_adtive',
        ),
    ]
