# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20171006_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Контактный номер'),
        ),
    ]
