# Generated by Django 2.0 on 2018-02-26 14:42

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20180226_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='card_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=user.models.make_random_password, max_length=25, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
