# Generated by Django 2.2.13 on 2021-05-12 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20200802_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(verbose_name='Когда была зарегистрирована')),
                ('money_came', models.FloatField(verbose_name='Сколько пришло денег')),
                ('source', models.CharField(blank=True, max_length=10, null=True, verbose_name='Из какого источника пришли деньги')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='На чей user_id пришли деньги')),
            ],
        ),
    ]
