# Generated by Django 2.2.13 on 2021-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_moneytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_number',
            field=models.CharField(max_length=10, verbose_name='Номер группы'),
        ),
    ]
