# Generated by Django 2.1.1 on 2018-09-30 22:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import precise_bbcode.fields
import utils.model_aliases


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('location', models.CharField(blank=True, max_length=124, null=True, verbose_name='Расположение')),
                ('_instruction_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('instruction', precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, null=True, verbose_name='Инструкция и описание')),
                ('image', utils.model_aliases.DefaultImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg'])], verbose_name='Изображение (jpg, jpeg, png, gif, svg)')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Последнее редактирование этих данных')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('responsible_room', models.CharField(blank=True, max_length=32, null=True, verbose_name='Комната ответственного')),
                ('_announcements_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('announcements', precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, null=True, verbose_name='Объявления')),
                ('max_continuous_orders', models.PositiveSmallIntegerField(default=1, verbose_name='Максимум непрерывных заказов одного предмета')),
                ('days_to_show', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Дней на заказ')),
                ('timestep', models.TimeField(verbose_name='Минимальное время использования (шаг времени)')),
                ('default_works_from', models.TimeField(default=datetime.time(0, 0), verbose_name='Начало рабочего времени по-умолчанию')),
                ('default_works_to', models.TimeField(default=datetime.time(0, 0), verbose_name='Конец рабочего времени по-умолчанию')),
                ('time_after_now', models.TimeField(default=datetime.time(0, 20), verbose_name='Времени на запись после начала')),
                ('is_finished_hidden', models.BooleanField(default=True, verbose_name='Скрывать прошедшие интервалы')),
                ('time_margin_start', models.TimeField(default=datetime.time(0, 0), verbose_name='Время на вход до заказа')),
                ('time_margin_end', models.TimeField(default=datetime.time(0, 0), verbose_name='Время на вход после заказа')),
                ('disable_lock', models.BooleanField(default=False, verbose_name='ОТКЛЮЧИТЬ ЗАМКИ')),
                ('request_document', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'odt', 'png', 'jpg', 'jpeg'])], verbose_name='Служебка (doc/docx/pdf/odt/png/jpg/jpeg)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показа')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название/номер')),
                ('t_steps_per_order', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Число шагов времени на заказ')),
                ('extra_info', models.CharField(blank=True, max_length=124, null=True, verbose_name='Доп. информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Введено в строй')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показа')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meeting_room.MeetingRoom', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Комната (item)',
                'verbose_name_plural': 'Комнаты (item)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время конца')),
                ('used', models.BooleanField(default=False, verbose_name='Потрачено')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрено')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Назначение заказа')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='meeting_room.MeetingRoomItem', verbose_name='Комната (item)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_start', '-time_start'],
            },
        ),
    ]
