# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20171006_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Survey', verbose_name='Опрос'),
        ),
    ]
