# Generated by Django 2.0 on 2018-01-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_survey_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='report',
        ),
    ]
