# Generated by Django 2.0 on 2018-02-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_remove_survey_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to='surveys'),
        ),
    ]
