# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-started'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата ответа'),
        ),
    ]
