# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170814_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
