# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20170814_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='finished',
            field=models.DateTimeField(null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='started',
            field=models.DateTimeField(null=True, verbose_name='Дата начала'),
        ),
    ]
