# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20171013_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_rewrite',
            field=models.BooleanField(default=True, verbose_name='Разрешить исправлять'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Анонимный'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
