# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20171014_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdata',
            name='answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_data', to='survey.Answer', verbose_name='Результат'),
        ),
    ]
