# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20171014_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdata',
            name='answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_data', to='survey.Answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Анонимный (навсегда!))'),
        ),
    ]
