# Generated by Django 2.0 on 2017-12-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20171014_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers_data', to='survey.Survey', verbose_name='Опрос'),
            preserve_default=False,
        ),
    ]
