# Generated by Django 2.0 on 2017-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_answerdata_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='surveys'),
        ),
    ]
