# Generated by Django 2.0 on 2018-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to='surveys', verbose_name='Свежий отчёт'),
        ),
    ]
