# Generated by Django 2.0 on 2018-05-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20180212_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdata',
            name='answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_data', to='survey.Answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answerdata',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='survey.Survey', verbose_name='Опрос'),
        ),
    ]
