# Generated by Django 2.0 on 2018-02-12 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('edit_date', models.DateField(auto_now_add=True, verbose_name='Время редактирования')),
                ('text', models.CharField(max_length=512, verbose_name='Текст')),
                ('object_id', models.PositiveIntegerField(verbose_name='Id назначения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('object_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(('app_label', 'note'), ('model', 'question'), _connector='AND'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип назначения')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-create_date',),
            },
        ),
    ]
